### ISSUE TITLE
Pantheon desktop on GeckoLinux

### ISSUE THREAD

**Issue by awissu** [geckolinux/geckolinux-project#82] opened 2018-12-16 12:48 UTC
Hi, I'm one of the Pantheon maintainers. 
I think that a project can be considered stable.
If you are interested in this project, please visit this repository:
https://build.opensuse.org/project/show/X11:Pantheon:Branch

**Comment by Mazaduk** [comment] 2019-02-19 07:56
Oh, this would be interesting to see in GeckoLinux. Thanks for the link @awissu 

@geckolinux Are you planning on building new isos for when Leap 15.1 rolls around?

**Comment by geckolinux** [comment] 2019-02-19 11:32
> @geckolinux Are you planning on building new isos for when Leap 15.1 rolls around?

Definitely yes.

**Comment by Mazaduk** [comment] 2019-02-19 12:26
Do you think it would be possible to make a Pantheon iso? Looks like awissu's repo has been updated fairly recently and the packages seem to have built successfully (looking at the link).

**Comment by geckolinux** [comment] 2019-02-20 17:10
I'll definitely look into it. I'm leaving this bug report open so that I'll remember when the time comes.

**Comment by Kelvino9** [comment] 2019-02-22 12:37
That's great news. Looking forward to this project.
Been happily using some of your other flavors for a while already.

**Comment by Mazaduk** [comment] 2019-05-04 00:45
15.1 came out recently... Excited!
(On a separate note, how do you build gecko? Do you have a script? How did you write the script? I'm still a n00b but I wonder if I can assist Gecko and/or learn stuff [and be less n00by])

**Comment by geckolinux** [comment] 2019-05-04 02:58
Hi there, Leap 15.1 has not yet been released, it will be about another 3 weeks according to the roadmap:
https://news.opensuse.org/wp-content/uploads/2019/04/medium.png

GeckoLinux is built with [Kiwi](https://doc.opensuse.org/projects/kiwi/doc/), and these are the Kiwi config files I use:
https://github.com/geckolinux/geckolinux-project

**Comment by Mazaduk** [comment] 2019-05-04 05:55
ah whoops, my bad. I thought it'd already been out. Idk how these new
features like transactional updates work; maybe I'll understand someday haha

Do I just run ./config.sh?

**Comment by geckolinux** [comment] 2019-05-04 12:13
On 2019-05-04 12:55 a.m., Mazaduk wrote:
> Do I just run ./config.sh?

Nope, you're not compiling anything. You would following the general concepts explained here:
https://opensource.suse.com/kiwi/quickstart.html#build-your-first-image

`kiwi-ng --type iso system build --description /location/of/GeckoLinux/description --target-dir /tmp/wherever/you/want`

**Comment by Mazaduk** [comment] 2019-05-25 01:08
Did 15.1 come out yet? Officially?

**Comment by awissu** [comment] 2019-07-23 18:56
Now the project has the Live ISO images:
https://build.opensuse.org/project/show/X11:Pantheon:Branch:Medias
More info:  https://en.opensuse.org/Portal:Pantheon

**Comment by geckolinux** [comment] 2019-07-24 00:59
Wow... that's impressive to see. Thanks for the tip. I'll have to take Pantheon more seriously now for GeckoLinux.

**Comment by geckolinux** [comment] 2020-08-09 22:41
Hi everyone, could you please give this ISO a spin?
https://sourceforge.net/projects/geckolinux/files/testing/GeckoLinux_NEXT_Pantheon.x86_64-BETA-152.200809.0.iso/download

![Screenshot at 2020-08-09 16-57-38](https://user-images.githubusercontent.com/2692138/89743188-3477b080-da66-11ea-8297-8ef1f6773701.png)

Thanks to @awissu 's hard work, Pantheon seems to be in great shape for openSUSE Leap 15.2 in the `X11:Pantheon:Branch` repository. Just a few issues, maybe @awissu can comment:

- WiFI asks for the password twice
     - Probably related to the above, had to include `NetworkManager-applet`, otherwise it wouldn't store the WiFI password unless manually changing it to be stored for all users on the system.
     - Then, when the WiFI connection is finally established, at any rate it gets stored as a system-wide connection controllable by all users.
- Window half-tiling by dragging to the screen edge and releasing does not exist, despite the relevant dconf option being enabled.
- I manually added the `.contractor` files that are needed for file-roller integration into the context menu in Patheon Files, it would be nice to have them come with the RPM package.

Apart from that, it's working impressively well. Seems to be fast and stable and aesthetically pleasing. I'm using the elementary theme instead of Numix because Pantheon doesn't look too great with Numix, although it is usable. I'd like your opinions on which you prefer. I also tested Plata, but its light variants have incorrect transparency for Wingpanel.

It would be fun to produce a ROLLING spin of this too, except that Pantheon Files is currently broken for Tumbleweed. :thinking: 

Any other issues?

**Comment by awissu** [comment] 2020-08-11 16:36
> Probably related to the above, had to include NetworkManager-applet, otherwise it wouldn't store the WiFI password unless manually changing it to be stored for all users on the system.

I had excluded NetworkManager-applet as recommended dependency:
https://build.opensuse.org/package/rdiff/X11:Pantheon/wingpanel-indicator-network?linkrev=base&rev=9
You can install this package when building an image.

> Apart from that, it's working impressively well. Seems to be fast and stable and aesthetically pleasing. I'm using the elementary theme instead of Numix because Pantheon doesn't look too great with Numix...

https://github.com/elementary/default-settings/issues/164

**Comment by geckolinux** [comment] 2020-08-11 22:11
> > Probably related to the above, had to include NetworkManager-applet, otherwise it wouldn't store the WiFI password unless manually changing it to be stored for all users on the system.
> 
> I had excluded NetworkManager-applet as recommended dependency:
> https://build.opensuse.org/package/rdiff/X11:Pantheon/wingpanel-indicator-network?linkrev=base&rev=9
> You can install this package when building an image.

Thanks, `NetworkManager-applet` is included in the above ISO beta image.

By any chance is there a fix for this?

![Screenshot from 2020-08-11 17 08 05](https://user-images.githubusercontent.com/2692138/89953803-6bc89780-dbf5-11ea-8741-9597d0f953dd.png)

It happens when establishing the connection, and at every reboot, and sometimes after resuming from suspend. Possibly a PolicyKit action? Although it appears that the root of the problem is that the Pantheon network configurator is trying to establish a system-wide connection, whereas NetworkManager normally creates it just for the user.

**Comment by awissu** [comment] 2020-08-12 16:47
Please check your settings:
nm-connection-editor -> Wi-Fi (system-connection) -> Authenticate to edit the selected connection -> General -> All users may connect to this network

**Comment by geckolinux** [comment] 2020-08-12 17:29
Thanks @awissu , that is a good workaround. I think it's still not ideal though, because 1) the Pantheon network manager (which almost all users will use because it interfaces with the wingpanel network control) creates connections by default for All users. And 2) on my non-Pantheon openSUSE systems I actually configure my WiFI connection for All Users to connect, but it doesn't require the root password.

**Comment by awissu** [comment] 2020-08-12 17:35
Sorry, but this nm-connection-editor default setting .

**Comment by geckolinux** [comment] 2020-08-12 17:52
Could a PolicyKit policy be included possibly so that it doesn't ask for the password?

**Comment by awissu** [comment] 2020-08-12 18:03
See files:
```
usr/share/polkit-1/actions/org.freedesktop.NetworkManager.policy
etc/polkit-1/rules.d/90-default-privs.rules:            'org.freedesktop.NetworkManager.settings.modify.system':
etc/polkit-default-privs.easy:org.freedesktop.NetworkManager.settings.modify.system           auth_admin_keep
etc/polkit-default-privs.restrictive:org.freedesktop.NetworkManager.settings.modify.system           auth_admin_keep
etc/polkit-default-privs.standard:org.freedesktop.NetworkManager.settings.modify.system           auth_admin_keep
```
and NetworkManager.conf -> main section -> auth-polkit: https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html

**Comment by awissu** [comment] 2020-08-12 18:07
```
su
echo 'org.freedesktop.NetworkManager.settings.modify.system auth_admin_keep:yes:yes' >> /etc/polkit-default-privs.local
/sbin/set_polkit_default_privs
```

**Comment by geckolinux** [comment] 2020-08-12 18:12
On 12/08/2020 13:03, Alexei Podvalsky wrote:
> and NetworkManager.conf -> main section -> auth-polkit: https://developer.gnome.org/NetworkManager/stable/NetworkManager.conf.html

Thank you, this is helpful. I applied the option:
auth-polkit=false
And now PolKit no longer requests the root password. That's a big improvement.

The only remaining bug now is that when using the Pantheon network GUI to add a new WiFI connection, it asks for the password twice.

**Comment by awissu** [comment] 2020-08-12 19:23
> It would be fun to produce a ROLLING spin of this too, except that Pantheon Files is currently broken for Tumbleweed. thinking

This issue is fixed in the current version.

**Comment by geckolinux** [comment] 2020-08-12 20:14
> > It would be fun to produce a ROLLING spin of this too, except that Pantheon Files is currently broken for Tumbleweed. thinking
> 
> This issue is fixed in the current version.

Great work @awissu ! Really appreciate it. So, it's looking like the independence from Gnome in the X11:Pantheon:Branch repo is the best way to go. Will you soon be migrating the X11:Pantheon:Branch to the main X11:Pantheon repo? I'd like to know before I officially release any ISOs.

**Comment by awissu** [comment] 2020-08-12 21:07
X11:Pantheon this is an independent branch for upstream packages (experimental). The project is unlikely to change in the short term.
X11:Pantheon:Branch required to freeze the main components of the Pantheon desktop.

**Comment by geckolinux** [comment] 2020-08-22 20:01
We're so close to a release of the GeckoLinux Pantheon spins! I'm just waiting for a major issue to be resolved with the 5.8 kernel in Tumbleweed that is currently preventing the live ISO from working correctly, and as for the Leap 15.2 based version there's a new issue that recently appeared with missing buttons in the Pantheon file chooser module for GTK. As soon as those are resolved we'll have quite a treat I think.

I'm trying to figure out how to name and categorize the two Pantheon editions. The Leap-based one would logically be called **GeckoLinux _NEXT_ Pantheon**, since it uses OBS repos like the **GeckoLinux _NEXT_ Plasma** edition. But then I don't know how to categorize the edition based on Tumbleweed, since it also uses OBS repos...

**Comment by awissu** [comment] 2020-08-22 20:22
openSUSE Leap 15.2 still is using glibc 2.26. Therefore, distribution supports Pantheon 5.x.x from elementary OS 5.x.x.
Tumbleweed will contain the next version, i.e Pantheon 6.x.x from elementary OS 6.x.x.

**Comment by geckolinux** [comment] 2020-08-22 20:25
> openSUSE Leap 15.2 still is using glibc 2.26. Therefore, distribution supports Pantheon 5.x.x from elementary OS 5.x.x.
Tumbleweed will contain the next version, i.e Pantheon 6.x.x from elementary OS 6.x.x.

Ah, interesting, so there will be real value to a having both Leap and Tumbleweed based ISOs. Great work @awissu !

**Comment by geckolinux** [comment] 2020-09-02 05:04
Here it is!
https://github.com/geckolinux/geckolinux-project/releases/tag/200830-Pantheon
Many thanks to @awissu for all his hard work!

**Closed as completed by geckolinux** 2020-09-02 05:04 UTC
Labels: enhancement, help wanted, upstream
