### ISSUE TITLE
How do I set up 3 monitors?

### ISSUE THREAD

**Issue by ideeman** [geckolinux/geckolinux-project#83] opened 2019-02-02 20:00 UTC
I am new to GeckoLinux, but a long time user of SuSE/openSuse.  I installed gecko yesterday and am very impressed.  This system has 3 monitors and 2 dual head video cards.  Both cards are NV Quadro NVS 290.  All 3 monitors are Samsung SyncMaster 150573.  I can use all 3 in openSuse, but can't find how to set the 3rd display up in Gecko.  Any help is appreciated.

**Comment by geckolinux** [comment] 2019-02-06 00:07
Hi there, sorry for the slow reply.

What desktop version are you using? I imagine you already tried the desktop environment's monitor configuration tool?

**Comment by ideeman** [comment] 2019-02-06 02:36
hello, yes I did.  I have two monitors running on a dual head video card.  The second video card is the same, but cannot start the 3rd monitor.

I am using geckolinux rolling version.  
GeckoLinux_ROLLING_LXQt.x86_64-999.180607.0

**Comment by geckolinux** [comment] 2019-02-06 04:28
Hmm OK. Could you please download and create a live USB of a GeckoLinux version with a more advanced desktop environment, such as Gnome or Plasma? I'd like to test if it's just a matter of the desktop environment's tools being able to handle the more advanced setup, or if the problem is at a hardware level.

**Comment by ideeman** [comment] 2019-02-22 03:51
I have been out of town for work.  I have downloaded Gnome and Cinnamon and will try this weekend.

**Comment by ideeman** [comment] 2019-03-07 14:47
I installed Cinnamon and it worked great running live from the usb as well as when installed.  Without any changes, boom 3 monitors.  Both rolling and static.  I think the issue is the NVidia.  I had been running opensuse with LXQT before trying Gecko, and the 3 monitors were fine.  It looks to be in the configuration or a driver vs in the desktop.  I still really like LXQT, but Cinnamon is great.

**Comment by geckolinux** [comment] 2019-03-07 21:57
OK, glad you got it working. So it appears that the LXQt monitor configuration tool is sub-optimal, but it should be possible to get it working still with the open source drivers, if it worked in Cinnamon. Sorry I'm really not knowledgeable about Nvidia hardware. OK if I close this bug report?

**Comment by ideeman** [comment] 2019-03-08 18:36
Works for me.
  I will play with some of the other tools to get it going.  Thanks for the help.

**Closed as completed** 2019-03-08 21:10 UTC
Labels: bug, cantfix, upstream
