### ISSUE TITLE
Unable to change brightness via hotkeys

### ISSUE THREAD

**Issue by yxinolija** [geckolinux/geckolinux-project#187] opened 2021-01-23 19:30 UTC
Hi, as title says im unable to change brightness either on installed gecko plasma or live one. Pressing Fn+F12 or F11 doesnt do anything, i have to manually adjust from Energy Saving screen. Machine is a Lenovo Ideapad, OpenSUSE works fine.

Thanks for any suggestions.

**Comment by geckolinux** [comment] 2021-01-23 20:41
Hi, which ISO did you try?

**Comment by yxinolija** [comment] 2021-01-23 22:24
GeckoLinux_ROLLING_Plasma.x86_64-999.210102.0

**Comment by yxinolija** [comment] 2021-01-28 01:02
And Linux Mint, OpenSUSE Tumbleweed, GeckoLinux Static just now.

**Comment by geckolinux** [comment] 2021-01-28 12:36
@yxinolija Thanks, do those other editions with Plasma have the same issue?

**Comment by yxinolija** [comment] 2021-01-28 12:47
Only in Gecko Rolling for some reason, the rest of distros are functional, Plasma or not.

**Comment by geckolinux** [comment] 2021-02-01 13:05
@yxinolija Thanks for reporting this, I can confirm this behavior on my test laptop as well. There must be a "recommended" package that is not being installed that is needed for this functionality. I'll have to track it down. Any suggestions or tips about which package it is would be welcome.

**Comment by yxinolija** [comment] 2021-02-01 13:35
I see. I'll see what I can find.

**Comment by geckolinux** [comment] 2021-02-01 17:15
Thanks for the help. As a suggestion, maybe try comparing the list of installed packages in the [current Tumbleweed live ISO](https://download.opensuse.org/tumbleweed/iso/openSUSE-Tumbleweed-KDE-Live-x86_64-Current.iso) with the GeckoLinux ISO.

**Comment by yxinolija** [comment] 2021-02-01 20:56
when i WinMerged the lists of installed packages i found some not installed. i tried installing missing packages: _intel-media-driver, intel-vaapi-driver, librdrm_intel1, ucode-intel, kernel-firmware-intel, acpica, cpupower, libvdpau-nouveau, Mesa-dri-nouveau_ with no changes. 

Also tried creating 20-intel.conf  from [here](https://forums.fedoraforum.org/showthread.php?311854-Brightness-keys-not-working-KDE-plasma), but it renders SDDM inactive(dead) with unable to display on vt7 or something. Deleting that file makes SDDM active again.

Kernel parameters _acpi_osi= , acpi_osi=Linux_ didnt help either.

EDIT:

i tried changing global shortcuts to something else, doesnt do a thing. Only some shortcuts displayed moving brightness bar that its going from 100% and down but brightness was still the same value.

**Comment by geckolinux** [comment] 2021-02-01 21:39
Thanks for the attempts. It's definitely a missing or included package that is causing the problem, because the Plasma Energy manager has the brightness slider and it works correctly, so it's not a kernel or ACPI issue.

**Comment by geckolinux** [comment] 2021-02-01 22:57
OK, I found the problem, it wasn't a missing package, but rather the config file `~/.config/kglobalshortcutsrc` . Try deleting that and it should fix it. I'll generate a new ISO with this fix ASAP, but unfortunately there's currently a blocking issue upstream:
http://bugzilla.opensuse.org/show_bug.cgi?id=1181620

Thanks to @yxinolija for reporting this important issue.

**Comment by yxinolija** [comment] 2021-02-01 23:02
Yeah, i forgot about that. No problem, glad i could help somehow.

**Comment by geckolinux** [comment] 2021-02-22 19:02
Fixed in https://github.com/geckolinux/geckolinux-project/releases/tag/210221.999

**Closed as completed by geckolinux** 2021-02-22 19:02 UTC
Labels: bug, todo, solved
