### ISSUE TITLE
upgrade leaves log in window as blackness . . . problem continues.

### ISSUE THREAD

**Issue by esteelpaz** [geckolinux/geckolinux-project#165] opened 2020-11-20 19:31 UTC
@geckolinux 

Just posting this as a "new" issue, because I posted a couple of times on my prior "closed" thread, didn't seem to bring any response . . . so:

Problem continues, unaddressed, in my Gecko rolling install . . . splash loads OK, then goes to black screen with vert cursor, have to type password in the black, then GUI opens OK. As posted MATE claims it isn't their problem, so looks like it's OpenSUSE issue, but only manifesting now in the Gecko install.

**Comment by geckolinux** [comment] 2020-11-20 20:08
Duplicate of #163

**Closed as completed by geckolinux** 2020-11-20 20:08 UTC
Labels: duplicate
