### ISSUE TITLE
Provide a 32-bit alternative for your rolling editions

### ISSUE THREAD

**Issue by lbssousa** [geckolinux/geckolinux-project#8] opened 2016-06-21 19:20 UTC
Have you ever considered the possibility to provide a 32-bit variant of your _rolling_ editions (I believe it could be done in SUSE Studio from an openSUSE 13.2 appliance, replacing default repos with Tumbleweed ones)? It could be valuable for low-profile computers, specially for LXQt and Xfce editions.

**Comment by geckolinux** [comment] 2016-06-22 01:36
Hello, this is a very good suggestion. I believe you are right about the 
possible path to converting an openSUSE 13.2 32-bit appliance into 
Tumbleweed 32-bit. I did consider it, and I also have a 32-bit laptop 
that I would love to run openSUSE on. But the problem is that openSUSE 
has very clearly showed that they don't care about 32-bit anymore, and 
as soon as a major issue arises with Tumbleweed 32-bit they have said 
they will drop it. So, I'm not sure if it would be worth the effort...

**Comment by lbssousa** [comment] 2016-06-28 18:41
I would like to try it myself anyway (I really want to build a 32-bit Tumbleweed in SUSE Studio and deploy it in our schools). If I clone your current ROLLING appliances and export their settings in KIWI format, do you know which files I would need to change in KIWI package to be able to import it in a new 13.2 32-bit appliance?

**Comment by geckolinux** [comment] 2016-06-28 19:17
Hi Laércio, I would be very interested to see what you come up with. I'm 
honestly not very familiar with Kiwi, sorry I can't be of more help.

**Comment by lbssousa** [comment] 2016-08-08 13:37
Another SUSE Studio user just gave me a quite valuable hint to clone an appliance while changing the architecture. Take a look at this page:

https://susestudio.com/help/api/using_api_with_curl.html

Basically, the command you need to clone a 64-bit appliance to a 32-bit target is the following:

```
curl -u <user>:<api_key> -XPOST "https://susestudio.com/api/v2/user/appliances?clone_from=<appliance_id>&name=My%20Clone%20Name&arch=i686"
```

This command should work even if the appliance you're cloning is based on Leap 42.1. That means you don't need to create a 13.2-based appliance for 32-bit architecture support. See this example:

https://susestudio.com/a/VU5ypu/opensuse-tumbleweed-kde3-live

**Comment by geckolinux** [comment] 2016-11-07 03:14
Thanks for the tips on this this. I still haven't found time to try this, so I'll close the issue for now.

**Closed as completed by geckolinux** 2016-11-07 03:14 UTC
